programa prueba;

peque animal {
    petite int clasificacion

    mini float resta(float b) {
        return b + clasificacion
    }
}

peque canino agranda animal {
    petite int nombre

    mini float suma(float a) {
        print("Estoy dentro")
        print(a)
        return a + nombre + clasificacion
    }
}

main() {
    petite float zury
    perro = new canino
    perro.nombre = 2
    perro.clasificacion = 3
    zury = perro.suma(5.0)
    print(zury)
}